### ISSUE TITLE
failed in ibm jdk 1.6.0.

### ISSUE THREAD

**Issue by kevinfujiang** [notnoop/java-apns#117]
Caused by: com.notnoop.exceptions.InvalidSSLConfig: com.notnoop.exceptions.InvalidSSLConfig: java.security.NoSuchAlgorithmException: sunx509 KeyManagerFactory not available
    at com.notnoop.apns.internal.Utilities.newSSLContext(Utilities.java:88)
    at com.notnoop.apns.ApnsServiceBuilder.withCert(ApnsServiceBuilder.java:167)
    at com.snda.dgnews.base.service.push.PushService.startApnsService(PushService.java:56)
    at com.snda.dgnews.base.service.push.PushService.<init>(PushService.java:39)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:44)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:516)
    at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:126)
    ... 54 more
# 
# java -version

java version "1.6.0"
Java(TM) SE Runtime Environment (build pxa6460sr13fp2-20130424_01(SR13 FP2))
IBM J9 VM (build 2.4, JRE 1.6.0 IBM J9 2.4 Linux amd64-64 jvmxa6460sr13fp2-20130423_146146 (JIT enabled, AOT enabled)
J9VM - 20130423_146146
JIT  - r9_20130108_31100ifx1
GC   - 20121212_AA)
JCL  - 20130419_01

**Comment by Hayllander** [comment]
Muito obrigado. Resolvido meu problema com esta dica. 
Só poderia acrescentar no post a maneira de gerar o pacote. Maven Goals -> assembly:single

Thank you very much. Solved my problem with this tip.
It could only add to the post the way to generate the package. Maven Goals -> assembly: single
