### ISSUE TITLE
java.net.ConnectException: Connection refused: connect

### ISSUE THREAD

**Issue by FruityFrank** [notnoop/java-apns#200]
Hello. This bug tracker may not be the correct place for me to post (I don't believe it's a bug), but I can't find anywhere else to post that question. I'm getting started using APNS and this project, and it never worked before.

**What steps will reproduce the problem?**

**What is the expected output? What do you see instead?**

I can't seem to connect to Apple sandbox servers using your project.

Command line arguments to run MainClass :

`s Path\to\keystore\apns_keystore_dev.p12 infos abcd`

The stacktrace :

`Sending message
Exception in thread "main" com.notnoop.exceptions.NetworkIOException: java.net.ConnectException: Connection refused: connect    at com.notnoop.apns.internal.ApnsConnectionImpl.getOrCreateSocket(ApnsConnectionImpl.java:301)
    at com.notnoop.apns.internal.ApnsConnectionImpl.sendMessage(ApnsConnectionImpl.java:322)
    at com.notnoop.apns.internal.ApnsConnectionImpl.sendMessage(ApnsConnectionImpl.java:311)
    at com.notnoop.apns.internal.ApnsServiceImpl.push(ApnsServiceImpl.java:46)
    at com.notnoop.apns.internal.AbstractApnsService.push(AbstractApnsService.java:56)
    at com.notnoop.apns.internal.ApnsServiceImpl.push(ApnsServiceImpl.java:1)
    at com.notnoop.apns.internal.AbstractApnsService.push(AbstractApnsService.java:1)
    at com.notnoop.apns.MainClass.main(MainClass.java:59)

Caused by: java.net.ConnectException: Connection refused: connect
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
    at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
    at java.net.Socket.connect(Socket.java:529)
    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:570)
    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.<init>(SSLSocketImpl.java:371)
    at com.sun.net.ssl.internal.ssl.SSLSocketFactoryImpl.createSocket(SSLSocketFactoryImpl.java:71)
    at com.notnoop.apns.internal.ApnsConnectionImpl.getOrCreateSocket(ApnsConnectionImpl.java:268)
    ... 7 more`

**What version of the product are you using? On what operating system?**

Java-apns 1.0.0.Beta5-SNAPSHOT
JDK 1.6.0_45
Windows 7

**Please provide any additional information below.**

Here is how I generated the "keystore" file "aps_keystore_dev.p12" from 2 .pem files :

`openssl pkcs12 -export -out aps_keystore_dev.p12 -inkey aps_private_key_dev.pem -in aps_certificate_dev.pem -certfile AppleWWDRCA.pem -passout "pass:infos"`

Note that the connection using the 2 .pem source files seems to work as per this command :

`openssl s_client -connect gateway.sandbox.push.apple.com:2195 -cert aps_certificate_dev.pem -key aps_private_key_dev.pem
Loading 'screen' into random state - done
connect: No error
connect:errno=0`

For info, I've posted the [same question @stackoverflow](http://stackoverflow.com/questions/26487952/apns-through-java-connection-refused).

Thanks for any pointer.

**Comment by ricksonmenezes** [comment]
@FruityFrank 

Can you please tell me how do I go about opening the 2195 port? Isn't this port on apple server as opposed to a machine that I can control via ssh?

```
public ApnsServiceBuilder withSandboxDestination() {
        return this.withGatewayDestination("gateway.sandbox.push.apple.com", 2195).withFeedbackDestination("feedback.sandbox.push.apple.com", 2196);
    }

    public ApnsServiceBuilder withProductionDestination() {
        return this.withGatewayDestination("gateway.push.apple.com", 2195).withFeedbackDestination("feedback.push.apple.com", 2196);
    }
```

Any insight is appreciated.
