### ISSUE TITLE
deadlock--

### ISSUE THREAD

**Issue by hahapig** [notnoop/java-apns#219]
Found one Java-level deadlock:
=============================
"Thread-55":
  waiting for ownable synchronizer 0x00000000c6769618, (a java.util.concurrent.locks.ReentrantLock$NonfairSync),
  which is held by "pool-2-thread-1"
"pool-2-thread-1":
  waiting to lock monitor 0x00007eff54002ba0 (object 0x00000000c6769038, a sun.security.ssl.SSLSocketImpl),
  which is held by "Thread-55"

Java stack information for the threads listed above:
===================================================
"Thread-55":
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000c6769618> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:834)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:867)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1197)
	at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:214)
	at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:290)
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:799)
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:672)
	at sun.security.ssl.SSLSocketImpl.sendAlert(SSLSocketImpl.java:2007)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1881)
	- locked <0x00000000c6769038> (a sun.security.ssl.SSLSocketImpl)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1844)
	- locked <0x00000000c6769038> (a sun.security.ssl.SSLSocketImpl)
	at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1808)
	- locked <0x00000000c6769038> (a sun.security.ssl.SSLSocketImpl)
	at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1753)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:113)
	- locked <0x00000000c676a600> (a sun.security.ssl.AppInputStream)
	at java.io.InputStream.read(InputStream.java:101)
	at com.notnoop.apns.internal.ApnsConnectionImpl$1MonitoringThread.run(ApnsConnectionImpl.java:114)
"pool-2-thread-1":
	at sun.security.ssl.SSLSocketImpl.getConnectionState(SSLSocketImpl.java:649)
	- waiting to lock <0x00000000c6769038> (a sun.security.ssl.SSLSocketImpl)
	at sun.security.ssl.SSLSocketImpl.isClosed(SSLSocketImpl.java:1446)
	at java.net.Socket.getTcpNoDelay(Socket.java:961)
	at sun.security.ssl.BaseSSLSocketImpl.getTcpNoDelay(BaseSSLSocketImpl.java:345)
	at sun.security.ssl.SSLSocketImpl.writeRecordInternal(SSLSocketImpl.java:819)
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:801)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:122)
	- locked <0x00000000c676aab0> (a sun.security.ssl.AppOutputStream)
	at java.io.OutputStream.write(OutputStream.java:75)
	at com.notnoop.apns.internal.ApnsConnectionImpl.sendMessage(ApnsConnectionImpl.java:240)
	- locked <0x00000000c65e8b58> (a com.notnoop.apns.internal.ApnsConnectionImpl)
	at com.notnoop.apns.internal.ApnsConnectionImpl.sendMessage(ApnsConnectionImpl.java:230)
	- locked <0x00000000c65e8b58> (a com.notnoop.apns.internal.ApnsConnectionImpl)
	at com.notnoop.apns.internal.ApnsPooledConnection$2.run(ApnsPooledConnection.java:47)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)

Found 1 deadlock.

**Comment by hahapig** [comment]
version:0.2.3

**Comment by hahapig** [comment]
java version "1.7.0_25"

**Comment by matzew** [comment]
tried the latest 1.0.0.Beta5?

On Thursday, January 29, 2015, tao.yang <notifications@github.com> wrote:

> version:0.2.3
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/notnoop/java-apns/issues/219#issuecomment-71993291>.
>


-- 
Sent from Gmail Mobile
