### ISSUE TITLE
Support Google App Engine

### ISSUE THREAD

**Issue by eliotstock** [notnoop/java-apns#238]
GAE doesn't allow thread creation. This line:

https://github.com/notnoop/java-apns/blob/master/src/main/java/com/notnoop/apns/internal/ApnsConnectionImpl.java#L120

will throw:

java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "modifyThreadGroup")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:382)
	at java.security.AccessController.checkPermission(AccessController.java:572)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at com.google.apphosting.runtime.security.CustomSecurityManager.checkPermission(CustomSecurityManager.java:56)
	at com.google.apphosting.runtime.security.CustomSecurityManager.checkAccess(CustomSecurityManager.java:131)
	at java.lang.ThreadGroup.checkAccess(ThreadGroup.java:315)
	at java.lang.Thread.init(Thread.java:391)
	at java.lang.Thread.init(Thread.java:349)
	at java.lang.Thread.<init>(Thread.java:675)
	at java.util.concurrent.Executors$DefaultThreadFactory.newThread(Executors.java:572)
	at com.notnoop.apns.internal.ApnsConnectionImpl$1.newThread(ApnsConnectionImpl.java:121)
	at com.notnoop.apns.internal.ApnsConnectionImpl.monitorSocket(ApnsConnectionImpl.java:136)
	at com.notnoop.apns.internal.ApnsConnectionImpl.getOrCreateSocket(ApnsConnectionImpl.java:294)
	at com.notnoop.apns.internal.ApnsConnectionImpl.sendMessage(ApnsConnectionImpl.java:322)
	at com.notnoop.apns.internal.ApnsConnectionImpl.sendMessage(ApnsConnectionImpl.java:311)
	at com.notnoop.apns.internal.ApnsServiceImpl.push(ApnsServiceImpl.java:46)
	at com.notnoop.apns.internal.AbstractApnsService.push(AbstractApnsService.java:56)
	at com.notnoop.apns.internal.ApnsServiceImpl.push(ApnsServiceImpl.java:36)
	at com.notnoop.apns.internal.AbstractApnsService.push(AbstractApnsService.java:45)

See: https://cloud.google.com/appengine/docs/java/#Java_The_sandbox

**Comment by eliotstock** [comment]
Duplicate of https://github.com/notnoop/java-apns/issues/107, sorry.
