### ISSUE TITLE
Dead Lock in 1.0 beta7

### ISSUE THREAD

**Issue by sammychen105** [notnoop/java-apns#240]
We found an dead lock in our test server.

Found one Java-level deadlock:
=============================
"MonitoringThread-264":
  waiting for ownable synchronizer 0x000000075e8c8068, (a java.util.concurrent.locks.ReentrantLock$NonfairSync),
  which is held by "pool-6-thread-1"
"pool-6-thread-1":
  waiting to lock monitor 0x00007f0378020230 (object 0x000000075e8c80f0, a sun.security.ssl.SSLSocketImpl),
  which is held by "MonitoringThread-264"

*more datails* :

Java stack information for the threads listed above:
===================================================
"MonitoringThread-264":
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000075e8c8068> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:834)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:867)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1197)
	at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:214)
	at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:290)
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:799)
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:672)
	at sun.security.ssl.SSLSocketImpl.sendAlert(SSLSocketImpl.java:2007)
	at sun.security.ssl.SSLSocketImpl.warning(SSLSocketImpl.java:1834)
	at sun.security.ssl.SSLSocketImpl.closeInternal(SSLSocketImpl.java:1602)
	- locked <0x000000075e8c80f0> (a sun.security.ssl.SSLSocketImpl)
	at sun.security.ssl.SSLSocketImpl.close(SSLSocketImpl.java:1538)
	at com.notnoop.apns.internal.Utilities.close(Utilities.java:250)
	at com.notnoop.apns.internal.ApnsConnectionImpl$2.run(ApnsConnectionImpl.java:157)
	at java.lang.Thread.run(Thread.java:722)
"pool-6-thread-1":
	at sun.security.ssl.SSLSocketImpl.getConnectionState(SSLSocketImpl.java:649)
	- waiting to lock <0x000000075e8c80f0> (a sun.security.ssl.SSLSocketImpl)
	at sun.security.ssl.SSLSocketImpl.isClosed(SSLSocketImpl.java:1446)
	at java.net.Socket.getTcpNoDelay(Socket.java:953)
	at sun.security.ssl.BaseSSLSocketImpl.getTcpNoDelay(BaseSSLSocketImpl.java:345)
	at sun.security.ssl.SSLSocketImpl.writeRecordInternal(SSLSocketImpl.java:819)
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:801)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:122)
	- locked <0x000000075e8c0370> (a sun.security.ssl.AppOutputStream)
	at java.io.OutputStream.write(OutputStream.java:75)
	at com.notnoop.apns.internal.ApnsConnectionImpl.sendMessage(ApnsConnectionImpl.java:328)
	- eliminated <0x0000000608236150> (a com.notnoop.apns.internal.ApnsConnectionImpl)
	at com.notnoop.apns.internal.ApnsConnectionImpl.sendMessage(ApnsConnectionImpl.java:312)
	- locked <0x0000000608236150> (a com.notnoop.apns.internal.ApnsConnectionImpl)
	at com.notnoop.apns.internal.ApnsServiceImpl.push(ApnsServiceImpl.java:46)

**Comment by sammychen105** [comment]
The bug in jvm causes this issue. we need a workaround to handle this. 
http://bugs.java.com/bugdatabase/view_bug.do?bug_id=8013809
