### ISSUE TITLE
AccessControlException caused by java policy

### ISSUE THREAD

**Issue by russellchadwick** [notnoop/java-apns#243]
java.lang.ExceptionInInitializerError
	at com.notnoop.apns.APNS.newService(APNS.java:55)
Caused by: java.security.AccessControlException: access denied (java.security.SecurityPermission getProperty.ssl.KeyManagerFactory.algorithm)
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:376)
	at java.security.AccessController.checkPermission(AccessController.java:549)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:532)
	at java.security.Security.getProperty(Security.java:725)
	at com.notnoop.apns.ApnsServiceBuilder.<clinit>(ApnsServiceBuilder.java:73)

**Comment by russellchadwick** [comment]
Our app runs with a policy file that restricts this code
https://github.com/notnoop/java-apns/blob/master/src/main/java/com/notnoop/apns/ApnsServiceBuilder.java#L73

There was a similar issue filed with another apns project due to Googles AppEngine limiting this as well
https://code.google.com/p/javapns/source/detail?r=378

**Comment by russellchadwick** [comment]
Fixed by adding this to the policy
	permission java.security.SecurityPermission
		"getProperty.ssl.KeyManagerFactory.algorithm";
