### ISSUE TITLE
failed to send push with exception: SSL peer shut down incorrectly 

### ISSUE THREAD

**Issue by teager** [notnoop/java-apns#263]
code:
public class App 
{
    public static void main( String[] args )
    {
    	ApnsService service =
    		    APNS.newService()
    		    .withCert("d:\\dds_dev.p12", "12345678")
    		    .withSandboxDestination()
    		    .build();
    	
    	String payload = APNS.newPayload().alertBody("Can't be simpler than this!").build();
    	String token = "9c7b20490c1241b1d23e8e0429fe87c9dff5f6d03f9a5e750da2434e94cdb8be";
    	service.push(token, payload);
    }
}

env:
jdk:jdk1.7.0_80
apns:1.0.0.Beta6

log:
2015-11-04 19:02:19.800 [main] DEBUG com.notnoop.apns.internal.Utilities - close java.io.FileInputStream@71a4e6f3
2015-11-04 19:02:19.938 [main] DEBUG c.n.apns.internal.ApnsConnectionImpl - sendMessage Message(Id=1; Token=9C7B20490C1241B1D23E8E0429FE87C9DFF5F6D03F9A5E750DA2434E94CDB8BE; Payload={"aps":{"alert":"Can't be simpler than this!"}}) fromBuffer: false
2015-11-04 19:02:20.764 [main] DEBUG c.n.apns.internal.ApnsConnectionImpl - Connected new socket 594c9066[SSL_NULL_WITH_NULL_NULL: Socket[addr=gateway.sandbox.push.apple.com/17.172.232.18,port=2195,localport=58229]]
2015-11-04 19:02:20.765 [main] DEBUG c.n.apns.internal.ApnsConnectionImpl - Launching Monitoring Thread for socket 594c9066[SSL_NULL_WITH_NULL_NULL: Socket[addr=gateway.sandbox.push.apple.com/17.172.232.18,port=2195,localport=58229]]
2015-11-04 19:02:20.769 [main] DEBUG c.n.apns.internal.ApnsConnectionImpl - Made a new connection to APNS
2015-11-04 19:02:20.769 [MonitoringThread-1] DEBUG c.n.apns.internal.ApnsConnectionImpl - Started monitoring thread
2015-11-04 19:02:21.382 [MonitoringThread-1] DEBUG c.n.apns.internal.ApnsConnectionImpl - Monitoring input stream closed by EOF
2015-11-04 19:02:21.383 [main] DEBUG com.notnoop.apns.internal.Utilities - close 594c9066[SSL_NULL_WITH_NULL_NULL: Socket[addr=gateway.sandbox.push.apple.com/17.172.232.18,port=2195,localport=58229]]
2015-11-04 19:02:21.676 [main] DEBUG c.n.apns.internal.ApnsConnectionImpl - Connected new socket 65d8446c[SSL_NULL_WITH_NULL_NULL: Socket[addr=gateway.sandbox.push.apple.com/17.172.232.18,port=2195,localport=58233]]
2015-11-04 19:02:21.677 [main] DEBUG c.n.apns.internal.ApnsConnectionImpl - Launching Monitoring Thread for socket 65d8446c[SSL_NULL_WITH_NULL_NULL: Socket[addr=gateway.sandbox.push.apple.com/17.172.232.18,port=2195,localport=58233]]
2015-11-04 19:02:21.678 [main] DEBUG c.n.apns.internal.ApnsConnectionImpl - Made a new connection to APNS
2015-11-04 19:02:21.678 [MonitoringThread-2] DEBUG c.n.apns.internal.ApnsConnectionImpl - Started monitoring thread
2015-11-04 19:02:22.331 [main] DEBUG com.notnoop.apns.internal.Utilities - close 65d8446c[SSL_NULL_WITH_NULL_NULL: Socket[addr=gateway.sandbox.push.apple.com/17.172.232.18,port=2195,localport=58233]]
2015-11-04 19:02:22.331 [MonitoringThread-2] DEBUG c.n.apns.internal.ApnsConnectionImpl - Monitoring input stream closed by EOF
2015-11-04 19:02:22.343 [main] INFO  c.n.apns.internal.ApnsConnectionImpl - Failed to send message Message(Id=1; Token=9C7B20490C1241B1D23E8E0429FE87C9DFF5F6D03F9A5E750DA2434E94CDB8BE; Payload={"aps":{"alert":"Can't be simpler than this!"}})... trying again after delay
javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:953) ~[na:1.7.0_80]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1332) ~[na:1.7.0_80]
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:709) ~[na:1.7.0_80]
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:122) ~[na:1.7.0_80]
	at java.io.OutputStream.write(OutputStream.java:75) ~[na:1.7.0_80]
	at com.notnoop.apns.internal.ApnsConnectionImpl.sendMessage(ApnsConnectionImpl.java:328) [apns-1.0.0.Beta6.jar:na]
	at com.notnoop.apns.internal.ApnsConnectionImpl.sendMessage(ApnsConnectionImpl.java:312) [apns-1.0.0.Beta6.jar:na]
	at com.notnoop.apns.internal.ApnsServiceImpl.push(ApnsServiceImpl.java:46) [apns-1.0.0.Beta6.jar:na]
	at com.notnoop.apns.internal.AbstractApnsService.push(AbstractApnsService.java:56) [apns-1.0.0.Beta6.jar:na]
	at com.notnoop.apns.internal.ApnsServiceImpl.push(ApnsServiceImpl.java:36) [apns-1.0.0.Beta6.jar:na]
	at com.notnoop.apns.internal.AbstractApnsService.push(AbstractApnsService.java:45) [apns-1.0.0.Beta6.jar:na]
	at push.test.App.main(App.java:22) [classes/:na]
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at sun.security.ssl.InputRecord.read(InputRecord.java:482) ~[na:1.7.0_80]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:934) ~[na:1.7.0_80]
	... 11 common frames omitted

Any help is going to be appreciated. :)

**Comment by JasonGaoG** [comment]
I have the same issue, the cert is NULL, SSL_NULL_WITH_NULL_NULL,but I don't know why...hope someone can help.

**Comment by szediwy** [comment]
Probably the same as issue #251?
