### ISSUE TITLE
Push notification sent but not received

### ISSUE THREAD

**Issue by hth** [notnoop/java-apns#265]
I am able to send push notification but App is not receiving it. I have verified,

- certificate is valid by using third party software to send push notification. 
- App receives push notification once sent using this third party --> https://github.com/noodlewerk/NWPusher.

What am I missing? Is anyone facing this issue?

**Comment by matzew** [comment]
weird - just wondering, does it work w/ Pushy (
https://github.com/relayrides/pushy) ?

On Fri, Nov 13, 2015 at 8:34 AM, hth <notifications@github.com> wrote:

> I am able to send push notification but App is not receiving it. I have
> verified certificate is valid by using third party software to send push
> notification. App receives push notification once sent using this third
> party --> https://github.com/noodlewerk/NWPusher.
>
> What am I missing? Is anyone facing this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/notnoop/java-apns/issues/265>.
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by hth** [comment]
I am trying that right now. Will let you know in 30 to 60 minutes max.

**Comment by matzew** [comment]
awesome, thanks for checking!

On Fri, Nov 13, 2015 at 9:00 AM, hth <notifications@github.com> wrote:

> I am trying that right now. Will let you know in 30 to 60 minutes max.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/notnoop/java-apns/issues/265#issuecomment-156357447>.
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by hth** [comment]
Pushy is working. Tested it twice. 
If you need anything from me please let me know. 
Using Beta6 version.

**Comment by matzew** [comment]
weird - mind sharing the code you are using ?

**Comment by hth** [comment]
Listing just APNS code.

    this.apnsService = APNS.newService()
                    .withCert(this.getClass().getClassLoader().getResourceAsStream("/cert/xxx_credentials.p12"), apnsCertificatePassword)
                    .withProductionDestination().withDelegate(getDelegate())
                    .build();


    private ApnsDelegate getDelegate() {
        return new ApnsDelegate() {
            public void notificationsResent(int resendCount) {
                LOG.info("resendCount={}", resendCount);
            }

            public void messageSent(ApnsNotification message, boolean resent) {
                LOG.info("Message sent. Payload={}" + message);
            }

            public void messageSendFailed(ApnsNotification message, Throwable e) {
                LOG.error("Message send failed. Message={} token={} {} reason={}",
                        message.toString(), message.getDeviceToken().toString(), message.getPayload().toString(), e.getLocalizedMessage(), e);
            }

            public void connectionClosed(DeliveryError e, int messageIdentifier) {
                LOG.error("Connection closed. Message={}" + e.toString());
            }

            public void cacheLengthExceeded(int newCacheLength) {
                LOG.error("{}", newCacheLength);
            }
        };
    }

    String payload = APNS.newPayload()
                    .alertBody(message)
                    .sound("default")
                    .build();
    apnsService.push(registeredDevice.getToken(), payload);


Special case: This error occurred when used Pushy and APNS together. Order of execution APNS and the Pushy to same device token. 

    Failed to send message Message(Id=2; Token=D59CD408A977641C79D5B8CE8D9572458D8................; Payload={"aps":{"alert":"Welcome Vichyssoise. Hello","sound":"default"}})... trying again after delay

    java.net.SocketException: Connection closed by remote host
	at sun.security.ssl.SSLSocketImpl.checkWrite(SSLSocketImpl.java:1543) ~[na:1.8.0_40]
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:124) ~[na:1.8.0_40]
	at java.io.OutputStream.write(OutputStream.java:75) ~[na:1.8.0_40]
	at com.notnoop.apns.internal.ApnsConnectionImpl.sendMessage(ApnsConnectionImpl.java:328) [apns-1.0.0.Beta6.jar:na]
	at com.notnoop.apns.internal.ApnsConnectionImpl.sendMessage(ApnsConnectionImpl.java:312) [apns-1.0.0.Beta6.jar:na]
	at com.notnoop.apns.internal.ApnsServiceImpl.push(ApnsServiceImpl.java:46) [apns-1.0.0.Beta6.jar:na]
	at com.notnoop.apns.internal.AbstractApnsService.push(AbstractApnsService.java:56) [apns-1.0.0.Beta6.jar:na]
	at com.notnoop.apns.internal.ApnsServiceImpl.push(ApnsServiceImpl.java:36) [apns-1.0.0.Beta6.jar:na]
	at com.notnoop.apns.internal.AbstractApnsService.push(AbstractApnsService.java:45) [apns-1.0.0.Beta6.jar:na]
	at com....................]
	at com....................]
	at com....................]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_40]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_40]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_40]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_40]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_40]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_40]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_40]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_40]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]

**Comment by hth** [comment]
I think I found the problem

**Comment by matzew** [comment]
you are using production w/ sandbox/dev token?

**Comment by hth** [comment]
:) Yes. My sandbox certificate is assigned to .withProductionDestination(). So they are switched. Testing  and will let you know.

**Comment by matzew** [comment]
I agree, that the error handling is not best



On Fri, Nov 13, 2015 at 11:08 AM, hth <notifications@github.com> wrote:

> :) Yes. My sandbox certificate is assigned to
> .withProductionDestination(). So they are switched. Testing and will let
> you know.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/notnoop/java-apns/issues/265#issuecomment-156384315>.
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by hth** [comment]
So that worked. Thats was completely my mistake and after switching destination target it worked. By the way, I really appreciate the API you are supporting. It has made life easy. Error handling can be aimed for 1.1 release. Looking forward to 1.0 Release. 

Hope I have made you feel good. Don't forget to drink beer tonight :)

**Comment by matzew** [comment]
the delegate is handy - yes, we use that in our Push Server too.

**Comment by matzew** [comment]
:beers: cheers, @hth

**Comment by hth** [comment]
:beers: cheers, @matzew Thanks :) 

Marking its a closed issue.
