### ISSUE TITLE
NetworkIOException: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake

### ISSUE THREAD

**Issue by santosh-1987** [notnoop/java-apns#301]
**Hi Team,**
_ We are facing this issue from last 5 days, please help in resolving it .

_> 2016-04-13 10:10:02,275 [pool-1-thread-1] INFO  com.accentuer.ae.push.dao.impl.DeviceLRSProcessor - About to process com_ipcmedia_countrylife_int
2016-04-13 10:10:02,317 [pool-1-thread-1] INFO  com.accentuer.ae.push.dao.impl.JdbcTokenAccessor - Now processing without throttling 100
2016-04-13 10:10:02,338 [pool-1-thread-1] INFO  com.accentuer.ae.push.services.APNSService - About to send 298755 - 100
2016-04-13 10:12:36,589 [pool-2-thread-4] INFO  com.accentuer.ae.push.apns.ApnsDelegateImpl - Message sent failed Remote host closed connection during handshake
2016-04-13 10:12:36,591 [pool-1-thread-1] WARN  com.accentuer.ae.push.services.APNSService - com_ipcmedia_countrylife_int Error posting to multiple devices
```
com.notnoop.exceptions.NetworkIOException: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at com.notnoop.apns.internal.Utilities.wrapAndThrowAsRuntimeException(Utilities.java:284)
	at com.notnoop.apns.internal.ApnsConnectionImpl.sendMessage(ApnsConnectionImpl.java:342)
	at com.notnoop.apns.internal.ApnsConnectionImpl.sendMessage(ApnsConnectionImpl.java:312)
	at com.notnoop.apns.internal.ApnsPooledConnection$2.call(ApnsPooledConnection.java:43)
	at com.notnoop.apns.internal.ApnsPooledConnection$2.call(ApnsPooledConnection.java:41)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:701)
Caused by: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:941)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1320)
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:698)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:119)
	at java.io.OutputStream.write(OutputStream.java:75)
	at com.notnoop.apns.internal.ApnsConnectionImpl.sendMessage(ApnsConnectionImpl.java:328)
	... 8 more
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at sun.security.ssl.InputRecord.read(InputRecord.java:482)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:922)
	... 13 more
```

> 2016-04-13 10:12:36,593 [pool-1-thread-1] INFO  com.accentuer.ae.push.dao.impl.JdbcTokenAccessor - Now processing without throttling 200
> 2016-04-13 10:12:36,605 [pool-1-thread-1] INFO  com.accentuer.ae.push.services.APNSService - About to send 298755 - 100
> 2016-04-13 10:15:41,245 [pool-2-thread-5] INFO  com.accentuer.ae.push.apns.ApnsDelegateImpl - Message sent failed Remote host closed connection during handshake
> 2016-04-13 10:15:41,245 [pool-1-thread-1] WARN  com.accentuer.ae.push.services.APNSService - com_ipcmedia_countrylife_int Error posting to multiple devices
> com.notnoop.exceptions.NetworkIOException: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
> 	at com.notnoop.apns.internal.Utilities.wrapAndThrowAsRuntimeException(Utilities.java:284)
> 	at com.notnoop.apns.internal.ApnsConnectionImpl.sendMessage(ApnsConnectionImpl.java:342)
> 	at com.notnoop.apns.internal.ApnsConnectionImpl.sendMessage(ApnsConnectionImpl.java:312)
> 	at com.notnoop.apns.internal.ApnsPooledConnection$2.call(ApnsPooledConnection.java:43)
> 	at com.notnoop.apns.internal.ApnsPooledConnection$2.call(ApnsPooledConnection.java:41)
> 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
> 	at java.lang.Thread.run(Thread.java:701)
> Caused by: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
> 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:941)
> 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1320)
> 	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:698)
> 	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:119)
> 	at java.io.OutputStream.write(OutputStream.java:75)
> 	at com.notnoop.apns.internal.ApnsConnectionImpl.sendMessage(ApnsConnectionImpl.java:328)
> 	... 8 more
> Caused by: java.io.EOFException: SSL peer shut down incorrectly
> 	at sun.security.ssl.InputRecord.read(InputRecord.java:482)
> 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:922)
> 	... 13 more

	
```
2016-04-13 10:15:41,247 [pool-1-thread-1] INFO  com.accentuer.ae.push.dao.impl.JdbcTokenAccessor - Now processing without throttling 300
2016-04-13 10:15:41,256 [pool-1-thread-1] INFO  com.accentuer.ae.push.services.APNSService - About to send 298755 - 100
2016-04-13 10:15:41,908 [pool-1-thread-1] INFO  com.accentuer.ae.push.services.APNSService - Pushed Tokens to APNS Server
```

_This issue solves after restarting linux server and again starts after 1 hour , we are processing push notification in batch of 100 , it fails in few batches and sends to other batches . _

Any Help Would be appreciated, Every thing is OK with Certificates , it pushes notifications with the certificate , but throws error for few batches/devices.

**Comment by junweimah** [comment]
Have you resolved this issue yet? I am having the same problem

**Comment by danishin** [comment]
Encountering the same issue here. Certificate is fine as the server succeeds sending notification for >95% of the time, but it fails intermittently. Not sure what the cause is.

@santosh-1987 were you able to find the cause of this issue?
