### ISSUE TITLE
DEADLOCK in send and monithor threads

### ISSUE THREAD

**Issue by tarun14691** [notnoop/java-apns#310]
Env:
------------------------------------------
jvm : 1.7.0._45
========================
notnoop: 1.0.0.Beta6
========================

> **Monitor-thread-1: Received error for message that wasn't in the cache**.....

Such error happened with our production system. And after that everything goes in a deadlock for apns send thread.

There was a similar error raised in year 2014 and it was closed. But i think the issue is not resolved yet.

**Comment by superalex88** [comment]
I'm  sometimes facing same problem in our production system. send method is called but never ends nor a timeout happens

**Comment by ecalissendorff** [comment]
Noticed this issue also with  all my threads stuck trying to send a message:

    OS: Linux (4.2.0-19-generic)
    Architecture: amd64 64bit
    Java Home: /usr/lib/jvm/java-8-oracle/jre
    Java Version: 1.8.0_77
    JVM: Java HotSpot(TM) 64-Bit Server VM (25.77-b03, mixed mode)
    Java Vendor: Oracle Corporation

Thread dump of one of the stuck threads (15 in total)

"7-1223:PushHandler @ 2016-08-08 17:14:56" #15266 daemon prio=5 os_prio=0 tid=0x00007f9cf81bc800 nid=0x6432 waiting on condition [0x00007f9bf4e3d000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000c690de00> (a java.util.concurrent.FutureTask)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:429)
	at java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.notnoop.apns.internal.ApnsPooledConnection.sendMessage(ApnsPooledConnection.java:48)
	at com.notnoop.apns.internal.ApnsServiceImpl.push(ApnsServiceImpl.java:46)
	at com.notnoop.apns.internal.AbstractApnsService.push(AbstractApnsService.java:56)
	at com.notnoop.apns.internal.ApnsServiceImpl.push(ApnsServiceImpl.java:36)
	at com.notnoop.apns.internal.AbstractApnsService.push(AbstractApnsService.java:45)

   Locked ownable synchronizers:
	- <0x00000000c690d9f0> (a java.util.concurrent.ThreadPoolExecutor$Worker)
