### ISSUE TITLE
SSLHandshakeException: Received fatal alert: certificate_unknown

### ISSUE THREAD

**Issue by vlahakis** [notnoop/java-apns#320]
Although the implementation class works fine when running under Tomcat it fails when running directly as a JUnit test. Tried running on it's own without success.

The certificate is valid and I have added jssecacerts file under /Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre/lib/security folder (MAC).

I need to write a unit test for this implementation but cant get around this issue.

Exception:

> Exception in thread "main" com.notnoop.exceptions.NetworkIOException: javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown
	at com.notnoop.apns.internal.ApnsConnectionImpl.sendMessage(ApnsConnectionImpl.java:335)
	at com.notnoop.apns.internal.ApnsConnectionImpl.sendMessage(ApnsConnectionImpl.java:308)
	at com.notnoop.apns.internal.ApnsServiceImpl.push(ApnsServiceImpl.java:46)
	at com.notnoop.apns.internal.AbstractApnsService.push(AbstractApnsService.java:52)
	at com.notnoop.apns.internal.ApnsServiceImpl.push(ApnsServiceImpl.java:36)
	at com.notnoop.apns.internal.AbstractApnsService.push(AbstractApnsService.java:41)
	at com.company.Main.main(Main.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:1979)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1086)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1332)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:889)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:102)
	at com.notnoop.apns.internal.ApnsConnectionImpl$2.readPacket(ApnsConnectionImpl.java:237)
	at com.notnoop.apns.internal.ApnsConnectionImpl$2.run(ApnsConnectionImpl.java:149)
	at java.lang.Thread.run(Thread.java:745)

**Comment by vlahakis** [comment]
The issue was with the certificate itself. Tomcat was using a different one. Apologies. Closing
