### ISSUE TITLE
sendMessage error like this( javax.net.ssl.SSLException: Received fatal alert: internal_error)

### ISSUE THREAD

**Issue by freecs** [notnoop/java-apns#329]
## run MainClass.java throw excption, like below:_ 
Exception in thread "Jiaxin-APNS Thread 2" com.notnoop.exceptions.NetworkIOException: javax.net.ssl.SSLException: Received fatal alert: internal_error
	at com.notnoop.apns.internal.Utilities.wrapAndThrowAsRuntimeException(Utilities.java:245)
	at com.notnoop.apns.internal.ApnsConnectionImpl.sendMessage(ApnsConnectionImpl.java:346)
	at com.notnoop.apns.internal.ApnsConnectionImpl.sendMessage(ApnsConnectionImpl.java:313)
	at com.notnoop.apns.internal.ApnsServiceImpl.push(ApnsServiceImpl.java:46)
	at com.notnoop.apns.internal.AbstractApnsService.push(AbstractApnsService.java:56)
	at com.notnoop.apns.internal.ApnsServiceImpl.push(ApnsServiceImpl.java:1)
	at com.notnoop.apns.internal.AbstractApnsService.push(AbstractApnsService.java:1)
	at com.jxccp.apns.manager.ApnsManager$1.run(ApnsManager.java:179)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLException: Received fatal alert: internal_error
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:1979)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1086)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1332)
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:709)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:122)
	at java.io.OutputStream.write(OutputStream.java:75)
	at com.notnoop.apns.internal.ApnsConnectionImpl.sendMessage(ApnsConnectionImpl.java:329)
	... 9 more

**Comment by Mehdzor** [comment]
Today faced the issue. Any ideas?

**Comment by slippytoad** [comment]
Yep, same.

**Comment by Mehdzor** [comment]
Strange. It began to appear only today. It was working fine before.

**Comment by slippytoad** [comment]
I regenerated my cert and revoked the old one and it works again!

**Comment by Mehdzor** [comment]
<3 Will try it tomorrow.

**Comment by freecs** [comment]
@Mehdzor  Me too, it works before, the issue appears a few days ago.

**Comment by freecs** [comment]
@Mehdzor  find out the reason: p12 is out of date, regenerate the cert. Then it works.

**Comment by GoaPhuDen** [comment]
Today faced the issue :(
My app on develop server work normally but production server :( (with same cert)

**Comment by jerrychien** [comment]
<code>[[1] not transmitted to token 67de3..9783a  javax.net.ssl.SSLException: Received fatal alert: internal_error]</code>
also today found the issue, it works fine before, any idesa?

**Comment by kaiyuan01** [comment]
Same issue here. How to fix it?

**Comment by kaiyuan01** [comment]
Does anyone know how to fix the issue? I wrote a program that it works with JDK 1.6, but if I run it under JDK 1.7 or 1.8, it threw me the error above.

**Comment by avrshin** [comment]
has anyone found the solution or fix. i am facing same issue.

**Comment by bbb007** [comment]
has anyone found the solution or fix. i am facing same issue.
