### ISSUE TITLE
Problems With SSL Certificate

### ISSUE THREAD

**Issue by miltonhit** [notnoop/java-apns#353]
Hello,
We have been use this code a long time ago, today we have some problems with a SSLHandshake:

javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_expired
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2023)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:747)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
	at java.io.OutputStream.write(OutputStream.java:75)
	at com.notnoop.apns.internal.ApnsConnectionImpl.sendMessage(ApnsConnectionImpl.java:240)
	at com.notnoop.apns.internal.ApnsConnectionImpl.sendMessage(ApnsConnectionImpl.java:230)
	at com.notnoop.apns.internal.ApnsServiceImpl.push(ApnsServiceImpl.java:46)
	at com.notnoop.apns.internal.AbstractApnsService.push(AbstractApnsService.java:56)
	at com.notnoop.apns.internal.ApnsServiceImpl.push(ApnsServiceImpl.java:36)
	at com.notnoop.apns.internal.AbstractApnsService.push(AbstractApnsService.java:45) ...

Is this happening to you?
Version: 0.2.3

**Comment by miltonhit** [comment]
Sorry.

**Comment by kd8ssq** [comment]
@miltonhit did you ever figure out what the problem was?

**Comment by miltonhit** [comment]
Hello @kd8ssq I just generate a new certificate key.p12 in Apple

**Comment by kd8ssq** [comment]
@miltonhit Thanks.  Glad it's an easy fix.  Had the same problem come up this morning.
