### ISSUE TITLE
Recently started getting this error

### ISSUE THREAD

**Issue by amathias** [notnoop/java-apns#63]
Some background:

Here is how my code sends the APNS notification:

ApnsService service = serviceBuilder.build();

```
    service.start();

    PayloadBuilder pB = com.notnoop.apns.APNS.newPayload().alertBody(message).badge(badgeCount);

    if(!NO_SOUND.equalsIgnoreCase(sound)) {
        pB.sound(sound);
    }

    String payload =
        pB.build();

    logger.info("Attempting to send APNS payload : " + payload.toString());

    for(String token : tokens) {

        service.push(token, payload);
    }
    deleteInactiveDevices(service); // custom method
    service.stop();  // this is when the stack trace happens, stack trace is shown below
```

The notification reaches my phone successfully however I get the following error:

(com.notnoop.apns.internal.ApnsConnectionImpl$1MonitoringThread:112) WARN  Exception while waiting for error code
java.net.SocketException: socket closed
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.read(SocketInputStream.java:129)
    at com.sun.net.ssl.internal.ssl.InputRecord.readFully(InputRecord.java:293)
    at com.sun.net.ssl.internal.ssl.InputRecord.read(InputRecord.java:331)
    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:798)
    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:755)
    at com.sun.net.ssl.internal.ssl.AppInputStream.read(AppInputStream.java:75)
    at java.io.InputStream.read(InputStream.java:85)
    at com.notnoop.apns.internal.ApnsConnectionImpl$1MonitoringThread.run(ApnsConnectionImpl.java:102)

Again, as described in the commented code above, this error happens when I attempt to stop the service. It seems to be waiting on an error code. I think that I'm getting an error from Apple and im not handling it appropriately, but am not sure what to do. Is there something I am missing ?

(and obviously I know that i should not be starting and stopping the service for a single notification, but this is for testing)

Second issue:

Also, when i use this code on my company's website I get the following error:

at com.notnoop.apns.internal.Utilities.wrapAndThrowAsRuntimeException(Utilities.java:268)
    at com.notnoop.apns.internal.ApnsConnectionImpl.sendMessage(ApnsConnectionImpl.java:173)
    at com.notnoop.apns.internal.ApnsServiceImpl.push(ApnsServiceImpl.java:46)
    at com.notnoop.apns.internal.AbstractApnsService.push(AbstractApnsService.java:52)
    at com.notnoop.apns.internal.ApnsServiceImpl.push(ApnsServiceImpl.java:36)
    at com.omeda.mobile.APNS.sendAPNSNotification(APNS.java:124)
    at com.omeda.system.OperationsController.sendApnsNotification(OperationsController.java:1034)
    at org.apache.jsp.operations.appsettings.APNSTester_jsp._jspService(APNSTester_jsp.java:352)
    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:388)
    at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:313)
    at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:260)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at com.omeda.portal.security.SecurityFilter.doFilter(SecurityFilter.java:101)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:291)
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:859)
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:602)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:396)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)
Caused by: java.net.SocketException: Connection reset
    at java.net.SocketInputStream.read(SocketInputStream.java:168)
    at com.sun.net.ssl.internal.ssl.InputRecord.readFully(InputRecord.java:293)
    at com.sun.net.ssl.internal.ssl.InputRecord.read(InputRecord.java:331)
    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:830)
    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1170)
    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:637)
    at com.sun.net.ssl.internal.ssl.AppOutputStream.write(AppOutputStream.java:88)
    at java.io.OutputStream.write(OutputStream.java:58)
    at com.notnoop.apns.internal.ApnsConnectionImpl.sendMessage(ApnsConnectionImpl.java:161)

The socket gets reset, the 3 way handshake is performed, then nothing happens. Does anything stick out in this ?

Please if you know a solution post or email me at amathias@omeda.com. I am very worried about this and looking forward to a solution. I am using the jar file from this page which says it was last updated August, 2010 which has me worried, it was updated so long ago.

**Comment by Thantos1** [comment]
It's not an old certification problem because I can receive the notification mostly. Only a few sockets throw the "Conncection reset" exception.

**Comment by hgz07** [comment]
But I met many same exception, caused messages not receive.
@Thantos1 , How can I do ?

**Comment by moneydummy** [comment]
@Thantos1  can you solve the problem that you are facing "Conncection reset" exception.

**Comment by srikhakollu** [comment]
What this problem fixed.Can you share how this was fixed ?
