### ISSUE TITLE
Notifications stop working Pool or MINA

### ISSUE THREAD

**Issue by gonzajg** [notnoop/java-apns#70]
Hi, 
we tried your library with many notifications (millions a day) and at first it worked like a charm, but almost 15 minutes later, some stopped working and about 1 to 2 hours, none worked any more. We tried with nonblocking and with pool, and got the same result.
Here's our code: 
pool = APNS.newService()
                        .withCert(conf.getAppleCertificatePath(), conf.getApplePassword())
                        .withProductionDestination()
                        .withReconnectPolicy(Provided.EVERY_HALF_HOUR)
                        .asPool(30)
                        .build();

or without pool

pool = APNS.newService()
                        .withCert(conf.getAppleCertificatePath(), conf.getApplePassword())
                        .withProductionDestination()
                        .asNonBlocking()
                        .build();

pool.start()
...
pool.push(device_code, payload);

We got this logs from the servers (one for every connection and only once):

ApnsConnectionImpl [WARN] Exception while waiting for error code
java.net.SocketException: Socket closed
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.read(SocketInputStream.java:129)
    at com.sun.net.ssl.internal.ssl.InputRecord.readFully(InputRecord.java:293)
    at com.sun.net.ssl.internal.ssl.InputRecord.read(InputRecord.java:331)
    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:830)
    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:787)
    at com.sun.net.ssl.internal.ssl.AppInputStream.read(AppInputStream.java:75)
    at java.io.InputStream.read(InputStream.java:82)
    at com.notnoop.apns.internal.ApnsConnectionImpl$1MonitoringThread.run(ApnsConnectionImpl.java:102)

But I've seen this is harmless.

**Comment by yaogdu** [comment]
it gets a little bit slowly without non-blocking feature.
